name: Build & Test

on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
#          - beta
#          - nightly

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: build
        run: cargo build --verbose
      - name: test
        run: cargo test --verbose
