name: Build & Test

on:
  push:
  pull_request:
    branches:
      - main

env: 
  CARGO_TERM_COLOR: always

jobs:

  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build
        run: cargo build --verbose

  test:
    name: test
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: test
        run: cargo test --verbose
