name: Build & Test

on:
  push:
  pull_request:
    branches:
      - main

env: 
  CARGO_TERM_COLOR: always

jobs:

  setup:
    name: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
#          - beta
#          - nightly

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

  build:
    name: build
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        toolchain:
          - stable

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build
        run: cargo build --verbose

  test:
    name: test
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        toolchain:
          - stable

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: test
        run: cargo test --verbose
